name: vipay
description: vipay
publish_to: "none"
version: 2.0.6+31

environment:
  sdk: ">=2.8.0 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_swiper: ^1.1.6
  google_maps_flutter: ^1.0.6
  http: ^0.12.2
  intl: ^0.16.1
  html: ^0.14.0+4
  shared_preferences: ^0.5.12+4
  flutter_html: ^1.0.2
  location: ^3.0.2
  dynamic_theme: ^1.0.1
  flutter_inappwebview: ^4.0.0+4
  community_material_icon: ^5.4.55
  flutter_masked_text: ^0.8.0
  http_logger:
    path: lib/libraries/http_logger
  http_middleware:
    path: lib/libraries/http_middleware/
  google_sign_in: ^4.5.6
  intl_phone_number_input: ^0.5.2+2
  flutter_secure_storage: ^3.3.5
  local_auth: ^0.6.3+4
  progress_dialog: ^1.2.4
  fluttertoast: 7.1.4
  simple_animations: ^2.2.3
  date_range_picker: ^1.0.6
  expandable: ^4.1.4
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.7+12
  slide_popup_dialog: ^0.0.2
  flutter_webview_plugin: ^0.3.11
  random_color: ^1.0.5
  awesome_dialog: ^1.2.1
  qr_flutter: ^3.2.0
  percent_indicator: ^2.1.8
  keyboard_actions: ^3.3.1+1
  qrcode: ^1.0.4
  url_launcher: ^5.7.10
  flutter_widget_from_html: ^0.5.1+4
  pin_code_fields: ^6.0.0
  logger: ^0.9.4
  flare_flutter: ^2.0.6
  shimmer: ^1.1.2
  image_downloader: ^0.20.1
  flutter_rating_bar: ^3.2.0
  dotted_line: ^2.0.2
  simplest: ^0.0.2+3
  dotted_border: ^1.0.7
  package_info: ^0.4.3+2
  flutter_staggered_grid_view: ^0.3.2
  rating_bar: ^0.2.0
  flutter_slidable: ^0.5.7
  contacts_service: ^0.4.6
  permission_handler: ^5.0.1+1
  charts_flutter: ^0.9.0
  share: ^0.6.5+4
  path_provider: ^1.6.24
  carousel_slider: ^2.3.1
  #Stripe payment
  stripe_payment: ^1.0.8
  #Braintree payment
  flutter_braintree: ^1.1.0
  badges: ^1.1.4
  youtube_player_flutter: ^7.0.0+7
  freezed_annotation: ^0.12.0
  awesome_card: ^1.1.0
  signature: ^3.2.0
  multi_image_picker: ^4.7.14
  flutter_native_image: ^0.0.5+3
  flutter_countdown_timer: ^3.0.0
  #zoom image:
  pinch_zoom_image_last: ^0.3.2
  #Web view
  webview_flutter: ^2.0.2
  #dynamic links
  firebase_dynamic_links: ^0.6.3
  geocoding: ^1.0.5

dependency_overrides:
  intl: ^0.16.1
  webview_flutter: ^0.3.22+1
  flutter_svg: ^0.18.0
  analyzer: 0.40.6
  pull_to_refresh: 1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.2
  retrofit_generator: 1.4.0+2
  injectable_generator: ^1.0.6
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.3

# flutter pub get && flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: sfprotext
      fonts:
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Regular.otf
          weight: 300
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Bold.otf
          weight: 600
        - asset: assets/fonts/sfprotext/SF-Pro-Text-Semibold.otf
          weight: 700
    - family: vistolsans
      fonts:
        - asset: assets/fonts/vistolsanslight/VistolSans-Light.otf
    - family: worksans
      fonts:
        - asset: assets/fonts/worksans/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 200
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-Semibold.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
